[package]
name = "phoenix-bond"
version = "0.1.0"
authors = ["dongcool"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
uint = { version = "0.9.3", default-features = false }
near-sdk = "4.1.1"
near-sys = "0.2.0"
near-contract-standards = "4.1.1"
near-bigdecimal = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0", features = ["preserve_order"]}

[dev-dependencies]
rand = "0.8"

[features]
test = []
